***

<i class="fa fa-warning"></i> **Warning:**  The following schedule is a *tentative* guideline and will be evolving to meet course needs up to and during the semester.In particular, the pace of the course will be adjusted so that we move as possible conditional on everyone "getting" the material.

***

***


####  **Introduction to 6029 and R**

- **January 27**  Intro to the course  [Deck 1](lectures/Lecture_01.pdf)
    - In-class R Markdown example analysis: [Rmd source](docs/Challenger_Analysis.Rmd), [html output](docs/Challenger_Analysis.html)

- **January 27** Lab 1: Introduction to R, RStudio and knitr
    - Lab document: [html](Labs/lab1/lab1.html), [RMarkdown](Labs/lab1/lab1.Rmd)
    - Data: [gapminder.csv](data/gapminder.csv)
- **February 3** No Class
    -  Readings:
        - Data Camp "Introduction to R": [link here](https://www.datacamp.com/courses/free-introduction-to-r)    
- **February 10** Lab 2: Graphing and Data Manipulation
    - Lab document: [html](Labs/lab2/lab2_20.html)
    -  Readings:
        - Wickham, Hadley. 2010. ``A Layered Grammar of Graphics.'' *Journal of Computational and Graphical Statistics* 19(1): 3-28. [link here](http://dx.doi.org/10.1198/jcgs.2009.07098)
    - Probelm Set 1 Assigned, Due Feb 21

***


#### **Foundations of Linear Regression**

- **February 17**  Review, Properties and Assumptions, Matrix Form [Deck 2](lectures/Lecture_02.pdf)
    - Readings: 
        - Matrix algebra [handout](docs/matrix.pdf)
        

- **February 24**  February Break 
    - No  Class
- **March 2**  Lab 3:  Linear Regression, Matrices, and predicted Values
    - Lab document: [html](Labs/lab3/lab3.html)
    - Probelm Set 2 Assigned, Due March 13
    - Readings: 
        - Gelman and Hill, Ch. 2. [Concepts and methods from basic
probability and statistics](docs/gelman_hill_ch2.pdf)


***

#### **Assumptions & Properties of the Linear Regression Model, Part I**



- **March 9**  Lecture  [Deck 3](lectures/Lecture_03_handout.pdf)
    - [Sampling Distribution of linear regression example](https://www.econometrics-with-r.org/4-5-tsdotoe.html)

    - [Multiple regression coefficient anatomy](docs/mostly_harmless_ch3.pdf)

- **March 16** Lab 4: Multivariate Linear Regression, and Predicted Values
    - Lab document: [html](Labs/lab4/lab4.html)

***

#### **Assumptions & Properties of the Linear Regression Model, Part II**


- **March 23** Lecture  [Deck 4](lectures/Lecture_04_handout.pdf)

-  **March 30**  Sprnig break
    - No class

- **April 6**   Lab 5  Loops and simulation
    - Lab document: [html](Labs/lab5/lab5.html)
    - Probelm Set 3 Assigned, Due April 17

***

#### **Inference and Interpretation of Linear Regression**

- **April 20** Lecture  [Deck 5](lectures/Lecture_05_handout.pdf)

- **April 27** Lab 6: Binary Models and Data Wrangling
    - Lab document: [html](Labs/lab6/BinaryModelsAndDataWrangling.R)
    - Probelm Set 4 Assigned, Due May 3

- **May 4** Lab 7: Case Study
    - Lab document: [html](Labs/lab6/BinaryModelsAndDataWrangling.R)


***


#### **Poster Presentation and Final Paper**

- **May 13** Poster Presentation: 10:00 am
    - More info [here](posters.html)
- **May 16** Final Paper Due
    - More info [here](final_paper.html)

<!--


## Topic 2: Assumptions & Properties of the Linear Regression Model, Part I

### Monday, February 12

- [Deck 2](lectures/Lecture_02_handout.pdf)
- Readings: 
    - Matrix algebra readings. Read **any** of the following
        - Moore, Will H., and David A. Siegel. 2013. *A Mathematics Course for Political and Social Research*. 1st edition. Princeton, NJ: Princeton University Press, Chapter 12 (on Canvas).
        - Kevin Quinn's matrix algebra [handout](docs/matrix.pdf)
        - [CSSS Math Camp Lectures](http://www.csss.washington.edu/MathCamp/Lectures/) Section 4
	- Fox, Ch. 5, 9.1--9.2

### Monday, February 19

- No Class February Break


- Readings:

    - Hadley Wickham, [Introduction to dplyr](https://cran.rstudio.com/web/packages/dplyr/vignettes/introduction.html)

## Topic 3: Assumptions & Properties of the Linear Regression Model, Part II



- [Deck 3](lectures/Lecture_03_handout.pdf)
- [Sampling Distribution of linear regression example](https://raw.githubusercontent.com/POLS503/pols_503_sp15/master/lectures/Sampling_Distribution_Linear_Regression.Rmd)
- [Multiple regression coefficient anatomy](https://github.com/POLS503/pols_503_sp15/blob/master/lectures/multiple_regression_anatomy.R)
- Readings:

    - Fox, Ch. 6, 9.3
	
[Problem Set 1](hw/hw1.html) Due

- Lab document: [.Rmd](labs/lab3.Rmd), [html](labs/lab3.html)
- Readings

    - Wickham, Hadley. 2014. ``Tidy Data.'' *Journal of Statistical Software* 59(10). <http://www.jstatsoft.org/v59/i10/>.
    - Hadley Wickham, [tidyr vignette](https://cran.rstudio.com/web/packages/tidyr/vignettes/tidy-data.html)

## Topic 4: Statistical Inference / Interpretation of the Linear Model



- [Deck 4](lectures/Lecture_04_handout.pdf)
- Using R with the Duncan occupational prestige data [.Rmd](docs/Duncan_regression_example.Rmd), [.html](docs/Duncan_regression_example.html)
- Readings:

    - Fox, Ch. 6, 9.3



- Lab document: [.Rmd](labs/lab4.Rmd), [html](labs/lab4.html)
- Data: [ross_2012.csv](data/ross_2012.csv)
- Readings

    - **stargazer** [vignette](https://cran.r-project.org/web/packages/stargazer/vignettes/stargazer.pdf)
	- **broom** [vignette](https://cran.r-project.org/web/packages/broom/vignettes/broom.html)

## Topic 5: Model Fitting and Data Transformation



[Problem Set 2](hw/hw2.html) Due

- More on p-values and significance testing

    - Nuzzo, Regina. 2014. ``Scientific Method: Statistical Errors.'' *Nature* 506(7487): 150–52. <http://www.nature.com/doifinder/10.1038/506150a>

- Omitted Variable Bias

    - [Omitted Variable Bias handout](handout/OVB_Measurement_Error.pdf)
    - Fox, Ch. 6.3
    - Agrist and Pischke, Ch. 3.2.2


- Heteroskedasticity and misspecification

    - [OLS Residuals deck](lectures/Lecture_OLS_Residuals_presentation.pdf)
    - Fox, Ch 12.1--12.3
    - Angrist and Pischke, Ch. 8
	- King, Gary, and Margaret E. Roberts. 2015. ``How Robust Standard Errors Expose Methodological Problems They Do Not Fix, and What to Do About It.'' Political Analysis 23(2): 159–79. <http://pan.oxfordjournals.org/content/23/2/159>

- Mispecification, Transforming Covariates

    - See Christopher Adolph's slides from 503 last year <http://faculty.washington.edu/cadolph/503/topic5.pw.pdf>
    - Fox, Ch. 4, Ch 17.1--17.3
	- Gelman and Hill, Ch. 4.1--4.3, 4.5-4.6
	- Brambor, Thomas, William Roberts Clark, and Matt Golder. 2006. “Understanding Interaction Models: Improving Empirical Analyses.” Political Analysis 14(1): 63–82. <http://pan.oxfordjournals.org/content/14/1/63>
	


- Lab document: [.Rmd](labs/lab5.Rmd), [html](labs/lab5.html)

## Topic 6: Measurement Error, Transformations



We covered substantive vs. statistical influence; transformations; and measurement error.
You will need to cover collinearity, unusual and influential data, and robust regression on your own.

- The perils of stargazing:
    - Christopher Adolph, "Inference and Interpretation of Linear Regression", POLS 503, Spring 2014. <http://faculty.washington.edu/cadolph/503/topic4.pw.pdf#page=77>, pg. 77--.

- Transformations of Variables

    - Lecture deck: [.pdf](lectures/Lecture_Transformation_handout.pdf)

- Measurement error

    - Lecture deck: [.pdf](lectures/Lecture_Measurement_Error_handout.pdf)
    - Fox. Ch. 6.4
	
- Collinearity

    - Fox Ch 13 (13.1, skim the rest)




Lab notes: [.html](http://UW-POLS503.github.io/pols_503_sp15/labs/lab6.html), [.Rmd](http://pols503.github.io/pols_503_sp15/labs/lab6.Rmd)

## Topic 7: Interpretation, Model Selection



[Problem Set 3](hw/hw3.html) Due

- [Deck on Model Specification and Fit](lectures/Lecture_Model_Specification_handout.pdf)
- Life Expectancy Example: [.html](docs/Life_Expectancy_Example.html), [.Rmd](docs/Life_Expectancy_Example.Rmd)
- Interpretation of regression

    - King, Gary, Michael Tomz, and Jason Wittenberg. 2000. ``Making the Most of Statistical Analyses: Improving Interpretation and Presentation." *American Journal of Political Science* 44(2): 347–61. <http://www.jstor.org/stable/2669316>.

- Bootstrapping

    - Fox, Ch 21

- Model Selection and Cross-Validation

    - Fox, Ch 22



Lab notes: [.html](labs/lab7.html), [.Rmd](labs/lab7.Rmd)

## Topic 8: Causal Inference I



- Unusual and Influential Data and Robust Regression

    - Worked Example [Rmd](docs/Outliers_Robust_Regression.Rmd), [html](docs/Outliers_Robust_Regression.html)
    - Christopher Adolph, "Outliers and Robust Regression Techniques", POLS 503, Spring 2014. <http://faculty.washington.edu/cadolph/503/topic6.pw.pdf>
	- Readings
	
        - Fox, Ch 11, 19

- Missing Data

    - Slides on Missing Data [pdf](lectures/Lecture_Missing_Data_handout.pdf)
	- Worked Example [Rmd](docs/Imputing_Missing_Data.Rmd), [html](docs/Imputing_Missing_Data.html)
	- Readings:
	
        - King, Gary, James Honaker, Anne Joseph, and Kenneth Scheve. 2001. "Analyzing Incomplete Political Science Data: An Alternative Algorithm for Multiple Imputation." American Political Science Review 95: 49–69. Copy at http://j.mp/1zTTZUT

- Miscellaneous Thoughts on the state of quantitative analysis in political science. *We did not talk about this, but these are good readings*

    - Schrodt, Philip A. 2014. ``Seven Deadly Sins of Contemporary Quantitative Political Analysis.'' *Journal of Peace Research* 51(2): 287–300. <http://jpr.sagepub.com/content/51/2/287>
	- Achen, Christopher H. 2002. ``Toward a New Political Methodology: Microfoundations and ART.'' *Annual Review of Political Science* 5(1): 423–50. <http://dx.doi.org/10.1146/annurev.polisci.5.112801.080943>. Read the part on a "Rule of Three"; skim other parts.
	- Achen, Christopher H. 2005. ``Let’s Put Garbage-Can Regressions and Garbage-Can Probits Where They Belong.'' *Conflict Management and Peace Science* 22(4): 327–39. <http://cmp.sagepub.com/content/22/4/327> *skim*


### Monday, May 22

Lab document: [html](labs/lab8.html), [Rmd](labs/lab8.Rmd)

## Topic 9: Causal Inference II

### Monday, May 26

**Problem Set 4 Due**

- Limited Dependent Variables

    - Slides on the Linear Probability Model and Logit [pdf](lectures/Lecture_Binary_Dependent_Variables_handout.pdf)

- Potential outcomes framework, regression, matching

    - Slides on Casual Inference [pdf](lectures/Lecture_Causal_Inference_handout.pdf)
    - Readings

		- Gelman and Hill, Ch 9--10. 
		- Angrist and Pischke, Ch 1--3.
		- Angrist, Joshua D., and Jorn-Steffen Pischke. 2010. ``The Credibility Revolution in Empirical Economics: How Better Research Design Is Taking the Con out of Econometrics.'' *Journal of Economic Perspectives* 24(2): 3–30. <http://www.aeaweb.org/articles.php?doi=10.1257/jep.24.2.3> *For background reading*


### Monday, May 29

Lab document: [Rmd](labs/lab9.Rmd), [html](labs/lab9.html)

## Topic 10: Panel Data 

### Monday, June 2

- Slides on Panel data: [pdf](lectures/Lecture_Panel_Data_handout.pdf)
- Example with R code: [html](docs/panel.html), [Rmd](docs/panel.Rmd)
- Readings

    - Angrist and Pischke, Ch. 5, 8.2
    - Peter Kennedy, *A Guide to Econometrics*, 6th edition, Chapter 18, "Panel Data". On Canvas.
	- Wooldridge, *Econometric Analysis of Cross Section and Panel Data*, Chapter 10, "Basic Linear Unobserved Effects Panel Data Models". On Canvas.
	- Beck, N., & Katz, J. N. (2011). Modeling Dynamics in Time-Series–Cross-Section Political Economy Data. *Annual Review of Political Science*, 14(1), 331–352. <http://doi.org/10.1146/annurev-polisci-071510-103222>


### Monday, June 5

Open office hours to answer questions about your papers


* * * 

Syllabus derived from Christopher Adolph. (Spring 2014). *POLS/CSSS 503: Advanced Quantitative Political Methodology* [Syllabus]. University of Washington. http://faculty.washington.edu/cadolph/503/503.pdf [CC-BY-SA](https://creativecommons.org/licenses/by-sa/2.0/).

<!--  LocalWords:  UTC td href TAs García SAV gelman angrist UW eBook
 -->
<!--  LocalWords:  zuur Brambor TBD CSSS img src 221B Tu faq html
 -->
<!--  LocalWords:  wickham brambor
 -->
