*** 

### Final Paper


Submit a copy of the paper and all associated code and data necessary to produce the results of the paper (see rule 7) via Canvas

As in any graduate courses, strive to write, draft, or work on research that could turn into a publishable article.
There are several rules and recommendations for this assignment.

#### Rules

1. Students may work in pairs  on the assignment, or combine the paper with an assignment for another class.

2. Students may write a replication and extension of a published article or pursue an original analysis.
   

3. Except in cases of family or medical emergency, I will not grant incompletes.
   Think of this as a favor: I expect the paper to be the product of 15 weeks work, not a year, so turn in what you can accomplish in 15 weeks to get interim feedback, even if your ultimate research aims are broader than a term assignment.

4. The paper should be 15--20 pages long, but longer papers are acceptable.
   However, the quality of the analysis and clarity of presentation far outweigh the quantity of prose.

5. The main focus of the paper should be on data, methods, and results.
   Justify your modeling choices with reference to the data and present your findings in terms any intelligent person could understand, regardless of their statistical knowledge.
   This should not limit the sophistication of your methods: just think hard about how to explain results from complicated models in approachable terms.

6. Don’t spend too much time on literature reviews or theory but don’t neglect hypothesis building, either. (Note, however, that hypotheses often can be clearly explicated without recourse to numbered lists.) By the time I reach the results of your paper, I should have some idea what you expect, what would be surprising,    and why. I should also know why this matters.

7. **Students must provide the code and data necessary to produce the results in the paper.**
   Replication policies similar to this are already present in most top journals, and it is likely to be the standard everywhere soon.
   
   Provide instructions and documentation so that I can run the code and understand which code relates to various parts of your analyses. 
   
Put everything (including the paper, simplified data and  code) in a compressed file (e.g: .zip, .rar or .tar) and submit that compressed file  

#### Recommendations

1. Papers that ask interesting, novel, or controversial questions are better – potentially much better – than papers that do not, all else equal.

2. Papers that explain their empirical findings in ways non-specialists can understand are better than papers that do not, all else equal.

3. Model specifications informed by test statistics, substantive knowledge and theory are better than model specifications based solely on test statistics, all else equal.

4. Number pages, tables, figures, and sections of your paper for easy reference.
   Embed all figures and tables in the text, facing the same direction as the text,
   just as you would see in a book or journal.
   
5. Tables of regression results should be nicely formatted and selective.
   Do not just cut-and-paste from your statistical package. Do not star your estimates or provide redundant measures of uncertainty
   (standard errors and t-statistics); instead, provide substantively informative measures of uncertainty such as confidence
   intervals or standard errors.
   
6. Variable names should be readable, memorable, and clearly denote what the variable
   is: use Female rather than Gender, and Conservatism instead of Ideology.

7. Provide the reader with descriptive statistics of the data.
   Often, a correlation matrix helps too.
   The reader may be unfamiliar with your data, or at the very least, knows less about it than you.
   You are providing the reader context with which to understand your results.
   In so doing, you are also arming reader to pick apart your findings.
   That is a good thing.
   
8. Except when precision of presentation is paramount, use graphics rather than tables to present results.
   Graphics are easier to read, can convey more information, and are far more memorable than tables.

9. Scholars carefully craft prose, but often paste in graphics without a thought to making them elegant, clear, or effective.
   Graphics are as much a part of the paper as the words, and deserve as much attention---if not more---in design.

<!---
10. Start the paper immediately. Ideally, you should start the class with a research topic in mind.
   
11. If you have not done original quantitative research before, you will be surprised how long it takes to get original data.
If you are doing a replication, you will be surprised how hard it can be to get a replication dataset.

--->
