
***


### Poster Presentation

Creating an academic poster is very similar  creating _slides_ for a traditional presentation. Think of it as guide for you and your audience but at the end of the day *_you_* will be presenting it; it should only be a visual aid and not an article printed on a poster. 


#### Some basic guidelines. 

You don't have to include all of these or only these but these are the most common elements:

- A short introduction that gives the audience some context
- A Gap or puzzle to be solved
- A research question and/or hypotheses 
- Data
- Methods
- Results
- Conclusion and/or next steps
- A standard poster size is 48 x 36. Your poster can be slightly bigger or smaller but it's a good idea to keep it within those parameters.


#### Some tips for a succesful poster:

Some of the basic elements of successful traditional presentation apply here:

- Avoid too much text
- Avoid tables, use graphs!
- Make sure to have useful labels and titles in your graphs
- Apply efficient and  useful colors
- Use space wisely. Put your most important elements towards the center
- You can create beautiful posters using PowerPoint but I encourage you to use <span class="latex">L<sup>A</sup>T<sub>E</sub>X</span>. You can find a template [here](https://github.com/GarciaRios/govt_6029/raw/master/Labs/lab7/poster/ARA_poster_template.rar). 
    - Download all the files and run it to create a poster like [this](https://garciarios.github.io/govt_6029/Labs/lab7/poster/govt6029_poster.pdf)
    - This is just a template, you do not have to create one exactly like this one. Feel free to move things around


#### Submition guidelines and logistics

- TBA


<!--

- You will submit your poster  (pdf or PowerPoint only, no code) via Canvas by midnight May 23 
- At this point we will not have a poster presentation session but we will have one (hopefully) next semester

<!--
- We will formally begin with the poster presentations at 10:00 am on May 15
- Try to come a few minutes early so we can set up your poster
- I will bring some of those mounting adhesives. 
- Submit your poster (pdf or PowerPoint only, no code) via Blackboard by midnight on Wednesday
-->
